
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const GET_ITENANT_DETAIL = 'GET_ITENANT_DETAIL';
export const OPEN_TIME_SERVICES = 'OPEN_TIME_SERVICES';
export const INIT_SIGN = 'INIT_SIGN';
export const INIT_OUT_SIGN = 'INIT_OUT_SIGN';
